<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogInLab.Application\LogInLab.Application.csproj" />
    <ProjectReference Include="..\LogInLab.Domain\LogInLab.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Email\" />
    <Folder Include="Security\" />
    <Folder Include="Persistence\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
  </ItemGroup>

</Project>
